# Generated by Django 3.0.3 on 2020-03-30 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.SlugField(max_length=30, unique=True, verbose_name='user name'),
        ),
    ]
