# Generated by Django 3.0.3 on 2020-03-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200330_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='default-avatar.png', upload_to='avatar_images', verbose_name='Profile Image'),
        ),
    ]
