# Generated by Django 3.0.3 on 2020-04-01 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('institution', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='created date')),
                ('is_public', models.BooleanField(default=True, verbose_name='is conference publically accessible')),
                ('attendees', models.ManyToManyField(related_name='attendees_set', to=settings.AUTH_USER_MODEL)),
                ('attendees_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees_group', to='auth.Group')),
                ('guests', models.ManyToManyField(related_name='guests_set', to=settings.AUTH_USER_MODEL)),
                ('guests_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests_group', to='auth.Group')),
                ('organizers', models.ManyToManyField(related_name='organizers_set', to=settings.AUTH_USER_MODEL)),
                ('organizers_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizers_group', to='auth.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('title', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('created_date', models.DateTimeField(verbose_name='created date')),
                ('authors', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poster.Conference')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poster.Poster')),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
    ]
